server:
    ip-address: 172.20.138.97
    ip-address: 172.20.138.98
    ip-address: fd39:45ab:c123:1::1
    ip-address: fd39:45ab:c123:1::2
    port: 53
    username: nsd
    zonesdir: /etc/nsd/zones
    pidfile: ""

remote-control:
    control-enable: no

zone:
    name: backendservice.dn42
    zonefile: backendservice.dn42.zone

zone:
    name: 3.2.1.c.b.a.5.4.9.3.d.f.ip6.arpa
    zonefile: 3.2.1.c.b.a.5.4.9.3.d.f.ip6.arpa.zone

zone:
    name: 5.4.9.3.4.2.4.0.tel.dn42
    zonefile: 5.4.9.3.4.2.4.0.tel.dn42.zone

zone:
    name: 96/27.138.20.172.in-addr.arpa
    zonefile: 96_27.138.20.172.in-addr.arpa.zone
